language: python

python:
  - '3.0'
  - '3.5'
  - '3.6'

install:
  - pip install --upgrade paddlepaddle
  - pip install -r requirements.txt

script: true

notifications:
  email:
    on_success: change
    on_failure: always
